// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using STA.Worker.Data;

#nullable disable

namespace STA.Worker.Data.Migrations
{
    [DbContext(typeof(StaDbContext))]
    partial class StaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sta")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("STA.Worker.Data.Entities.LogProcesso", b =>
                {
                    b.Property<int>("CnLogProcesso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cn_log_processo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CnLogProcesso"));

                    b.Property<int>("CnProcesso")
                        .HasColumnType("integer")
                        .HasColumnName("cn_processo");

                    b.Property<int>("CnSistema")
                        .HasColumnType("integer")
                        .HasColumnName("cn_sistema");

                    b.Property<DateTime?>("DtFimProcesso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_fim_processo");

                    b.Property<DateTime>("DtInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_inicio")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("IdStatusProcesso")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("id_status_processo");

                    b.Property<long>("QtRegistrosErro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("qt_registros_erro");

                    b.Property<long>("QtRegistrosProcessados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("qt_registros_processados");

                    b.Property<long>("VlRegistrosErro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("vl_registros_erro");

                    b.Property<long>("VlRegistrosProcessados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("vl_registros_processados");

                    b.Property<string>("XmlObsProcesso")
                        .HasColumnType("text")
                        .HasColumnName("xml_obs_processo");

                    b.HasKey("CnLogProcesso");

                    b.HasIndex("DtInicio");

                    b.HasIndex("CnSistema", "CnProcesso");

                    b.ToTable("tbl_log_processo", "sta");
                });

            modelBuilder.Entity("STA.Worker.Data.Entities.ParametroSistema", b =>
                {
                    b.Property<int>("CnParametroSistema")
                        .HasColumnType("integer")
                        .HasColumnName("cn_parametro_sistema");

                    b.Property<int>("CnSistema")
                        .HasColumnType("integer")
                        .HasColumnName("cn_sistema");

                    b.Property<string>("CdParametroSistema")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cd_parametro_sistema");

                    b.HasKey("CnParametroSistema", "CnSistema");

                    b.HasIndex("CnSistema");

                    b.ToTable("tbl_parametro_sistema", "sta");
                });

            modelBuilder.Entity("STA.Worker.Data.Entities.Sistema", b =>
                {
                    b.Property<int>("CnSistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cn_sistema");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CnSistema"));

                    b.Property<string>("CdAliasSistema")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cd_alias_sistema");

                    b.HasKey("CnSistema");

                    b.HasIndex("CdAliasSistema")
                        .IsUnique();

                    b.ToTable("tbl_sistema", "sta");
                });

            modelBuilder.Entity("STA.Worker.Data.Entities.LogProcesso", b =>
                {
                    b.HasOne("STA.Worker.Data.Entities.Sistema", "Sistema")
                        .WithMany("Logs")
                        .HasForeignKey("CnSistema")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("STA.Worker.Data.Entities.ParametroSistema", b =>
                {
                    b.HasOne("STA.Worker.Data.Entities.Sistema", "Sistema")
                        .WithMany("Parametros")
                        .HasForeignKey("CnSistema")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("STA.Worker.Data.Entities.Sistema", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Parametros");
                });
#pragma warning restore 612, 618
        }
    }
}
